# Site wide configuration

title:            Simon's Scratch Book
locale:           en_US
url:              http://ssnl.github.io
url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Site owner
owner:
  name: Tongzhou Wang
  avatar: avatar.jpg
  bio: "Undergraduate studying computer science, statistics and philosophy at UC Berkeley"
  email: tongzhou.wang.1994@gmail.com
  disqus-shortname: ssnl
  twitter:
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: SsnL
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: tongzhouwang
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
